project:
  type: website

website:
  title: "Siddharth Singh (ISSS608: Visual Analytics)"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd"
    - text: "Take-Home Exercise"
      menu:
        - text: "Take-Home Exercise 1"
          href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.qmd"
        - text: "Take-Home Exercise 2"
          href: "Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.qmd"
    - text: "In-Class Exercise"
      menu:
        - text: "In-Class Exercise 3"
          href: "In-Class_Ex/In-Class_Ex03/In-Class_Ex03.qmd"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

